### ISSUE TITLE
Warnings about invalid XML Comments in generated code

### ISSUE THREAD

**Issue by pocki** [devlooped/ThisAssembly#408]
## Describe the Bug

Since the update to v2.0 I am getting warnings about invalid XML comments in the generated code.
It seems that there is cref used for referencing to Url - href should be used in this case, and cref to reference code.

## Steps to Reproduce
Update to v2.0

```
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Constants.BuildDateTime.g.cs(42,26,42,31): warning CS1584: XML comment has syntactically incorrect cref attribute 'https :  / / github . com / devlooped # sponsorlink'
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Constants.BuildDateTime.g.cs(42,64,42,64): warning CS1658: Unexpected character '#'. See also error CS1056.
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Branch.g.cs(42,26,42,31): warning CS1584: XML comment has syntactically incorrect cref attribute 'https :  / / github . com / devlooped # sponsorlink'
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Branch.g.cs(42,64,42,64): warning CS1658: Unexpected character '#'. See also error CS1056.
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Commit.g.cs(42,26,42,31): warning CS1584: XML comment has syntactically incorrect cref attribute 'https :  / / github . com / devlooped # sponsorlink'
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Commit.g.cs(42,64,42,64): warning CS1658: Unexpected character '#'. See also error CS1056.
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Sha.g.cs(42,26,42,31): warning CS1584: XML comment has syntactically incorrect cref attribute 'https :  / / github . com / devlooped # sponsorlink'
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Sha.g.cs(42,64,42,64): warning CS1658: Unexpected character '#'. See also error CS1056.
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Root.g.cs(42,26,42,31): warning CS1584: XML comment has syntactically incorrect cref attribute 'https :  / / github . com / devlooped # sponsorlink'
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Root.g.cs(42,64,42,64): warning CS1658: Unexpected character '#'. See also error CS1056.
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Url.g.cs(42,26,42,31): warning CS1584: XML comment has syntactically incorrect cref attribute 'https :  / / github . com / devlooped # sponsorlink'
\Debug\net8.0\ThisAssembly.Constants\ThisAssembly.ConstantsGenerator\Git.Url.g.cs(42,64,42,64): warning CS1658: Unexpected character '#'. See also error CS1056.
```

## Expected Behavior

XML comments should be generated correctly, no warning

## Exception with Stack Trace
no exception

## Version Info

```
    <PackageVersion Include="ThisAssembly.Constants" Version="2.0.0" />
    <PackageVersion Include="ThisAssembly.Git" Version="2.0.0" />
```

## Additional Info
.NET 8 project
Visual Studio 2022

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Fixed in https://github.com/devlooped/ThisAssembly/pull/409, shipping in 2.0.1

**Comment by OoLunar** [comment]
Still happening in 2.0.3:
```
/home/lunar/Code/OoLunar/Tomoe/src/obj/Debug/net8.0/ThisAssembly.Constants/ThisAssembly.ConstantsGenerator/Project.ProjectFile.g.cs(26,15): warning CS1570: XML comment has badly formed XML -- 'End tag 'summary' does not match the start tag 'Project'.'
/home/lunar/Code/OoLunar/Tomoe/src/obj/Debug/net8.0/ThisAssembly.Constants/ThisAssembly.ConstantsGenerator/Project.ProjectFile.g.cs(27,1): warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'summary'.'
```

I would provide the files if I could but unfortunately I cannot access them since they only exist when compiling.

**Comment by kzu** [comment]
You can view them by setting:

```xml
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
```

In your project. 
A small isolated repro (in particular, the contents of that `ProjectFile` property, which I suspect has newlines in it) would be super helpful. Alternatively, you can provide a comment for it that will override the default comment with just renders the value, like so:

```xml
<ItemGroup>
 <Constant Include="ProjectFile" Value="$(ProjectFile)" Comment="The contents of the project" Root="Project" />
</ItemGroup>
```
